/**
 * DO NOT EDIT THIS FILE WITHOUT PROPER KNOWLEDGE
 * THIS FILE IS PURELY FOR DEVELOPER PURPOSES ONLY
 *
 * TO EDIT USER FILE, USE 'config-user.js'
 *
 */
import _ from 'lodash';
/* eslint-disable import/extensions */
import { configProduction } from './config-production.js';
import { configDevelopment } from './config-development.js';
import { configUser } from './config-user.js';
import { configUniqueIds } from './config-unique-ids.js';
import { configLotLast } from './config-lot-last.js';
import { configContractors } from './config-contractors.js';
import { configLots } from './config-lots.js';
/* eslint-enable import/extensions */

const configBasic = {
    environment: 'development', // DON'T CHANGE THIS VALUE HERE
    timezone: 'Asia/Calcutta',
    timeOffsetInMinutesToAvoid: 2,
    appDomain: 'https://www.homenetiol.com',
    allottedFolderRegex: '^(\\d[\\S]*)(?: ([\\S| ]*))? ([\\S]+) (\\d{1,3}) \\((#(\\d{5}))\\)$',
    loggingFileLevel: 'billy',
    loggingConsoleLevel: 'billy',
    sendLogToNtfyUptoDate: '1990-01-01',
    browserArgs: {
        headless: false,
        defaultViewport: null,
        protocolTimeout: 0,
        executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
        args: [
            '--user-data-dir=C:\\Users\\Administrator\\AppData\\Local\\Google\\Chrome\\User Data',
            '--hide-crash-restore-bubble',
            '--window-size=1600,860',
        ],
    },
    sourceBookmarksFilePath: '..\\autodown_datastore\\Bookmarks_Source',
    processingBookmarksWithoutSyncFilePath: '..\\autodown_datastore\\Bookmarks',
    bookmarkOptions: {
        shouldIncludeFolders: true,
    },
    ignoreBookmarkURLS: [
        // {
        //     URLStartsWith: '',
        //     ignoreMesgInConsole: '',
        //     ignoreMesgInBookmark: '',
        // },
    ],
    urlCrawlingErrorsEligibleForRetrying: [
        //
    ],
    browserClosingErrors: [
        //
    ],
    dealerConfigurationPath: '.\\configs\\DealerConfiguration',
    downloadPath: '..\\autodown_datastore\\Downloads',
    contractorsZonePath: '..\\autodown_datastore\\ContractorsZone',
    contractorsRecordKeepingPath: '..\\autodown_datastore\\ContractorsRecordKeeping',
    uploadingZonePath: '..\\autodown_datastore\\UploadingZone',
    finishedUploadingZonePath: '..\\autodown_datastore\\FinishedUploadingZone',
    finishedAllotmentZonePath: '..\\autodown_datastore\\FinishedAllotmentZone',
    lockingBackupsZonePath: '..\\autodown_datastore\\LockingBackupsZone',
    reportsJSONPath: '..\\autodown_datastore\\Reports\\jsondata',
    reportsExcelOutputPath: '..\\autodown_datastore\\Reports\\generated',
    reportsMergedCopyPath: '..\\autodown_datastore\\Reports\\mergedcopy',
    isUpdateBookmarksOnceDone: false,
    isAutomaticClickSaveButtonOnUpload: false,
    cutterProcessingFolders: ['001_CuttingDone'], // The index of this array are used to detect the folder types, so check before you change
    cutterRecordKeepingFolders: ['002_CuttingAccounting'], // The index of this array are used to detect the folder types, so check before you change
    finisherProcessingFolders: ['003_FinishingBuffer', '004_ReadyToUpload'], // The index of this array are used to detect the folder types, so check before you change
    finisherRecordKeepingFolders: ['005_FinishingAccounting'], // The index of this array are used to detect the folder types, so check before you change
};

/**
 *
 * Check for what environment it is and merge
 * config files accordingly.
 *
 */
let configToExport = configBasic;
if (configUser.environment === 'production' || (configUser.environment === undefined && configBasic.environment === 'production')) {
    configToExport = _.merge(configToExport, configProduction);
} else if (configUser.environment === 'development' || (configUser.environment === undefined && configBasic.environment === 'development')) {
    configToExport = _.merge(configToExport, configDevelopment);
}
configToExport = _.merge(configToExport, configUser);
configToExport = _.merge(configToExport, configUniqueIds);
configToExport = _.merge(configToExport, configLotLast);
configToExport = _.merge(configToExport, configLots);
configToExport = _.merge(configToExport, configContractors);

const config = configToExport;

// eslint-disable-next-line import/prefer-default-export
export { config };
